graph TB

    subgraph Encoder
        Schema[Logical<br/>Schema]-->|Vectorize|Es[(E_s,E_p)]
    end

    subgraph LLM[TaxonomyLLM]
        Es-->H[(H_s,H_p)]
        H-->O[RDF<br/>Graph]
    end

    O-->|Materialize|T[Taxonomy<br/>Graph]

